# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.2.18

# Select what we should cache between builds
cache:
  paths:
  - vendor/

stages:
  - test
  - deploy

test:
  services:
    - mysql:5.7.19

  variables:
    MYSQL_DATABASE: database
    MYSQL_USER: runner
    MYSQL_ROOT_PASSWORD: password
    MYSQL_PASSWORD: password

  before_script:
    - curl -sS https://getcomposer.org/installer | php
    - apt-get update -yqq
    - apt-get install -yqq git unzip zlib1g-dev
    - apt install php-pcov
    - docker-php-ext-install pdo_mysql zip opcache php-pcov

  script:
    - echo "Running tests"
    - php composer.phar install
    - touch .env.test && echo -e $ENV_TEST_FILE >> .env.test
    - touch phpunit.xml && echo -e $PHPUNIT_XML >> phpunit.xml
    - php bin/console doctrine:migrations:migrate --env=test
    - php bin/console doctrine:fixtures:load --env=test
    - php -d pcov.enabled=1 bin/phpunit --coverage-text --colors=never tests/

deploy_staging:
  stage: deploy

  before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - touch .env.local && echo -e $ENV_STAGING_FILE >> .env.local

  script:
    - echo "Deploy to staging server"
    - > 
      ssh $STAGING_USER@$STAGING_HOST -p $STAGING_PORT 
      'cd staging.adriendesmet.com/ &&
      if [ -d fournieralice.com ]; then 
        rm -rf fournieralice.com/
      fi &&
      git clone https://gitlab.com/EyahDev/fournieralice.com.git &&
      cd fournieralice.com/ &&
      composer install --optimize-autoloader'
    - scp -P $STAGING_PORT .env.local $STAGING_USER@$STAGING_HOST:staging.adriendesmet.com/fournieralice.com/
    - ssh $STAGING_USER@$STAGING_HOST -p $STAGING_PORT
      'cd staging.adriendesmet.com/fournieralice.com/ &&
      /opt/alt/alt-nodejs8/root/usr/bin/npm install --scripts-prepend-node-path && /opt/alt/alt-nodejs8/root/usr/bin/npm run prod --scripts-prepend-node-path &&
      php bin/console doctrine:migrations:migrate --env=prod'

  environment:
    name: STAGING
    url: http://$STAGING_ENV_URL

  only:
    - dev
  
#deploy_prod:
#  stage: deploy
#  script:
#  only:
#    - master
